### ISSUE TITLE
New CRAN release?

### ISSUE THREAD

**Issue by edmcman** [aschleg/PetfindeR#4]
Could you make a new CRAN release?

**Comment by aschleg** [comment]
Hi, Edward!

Apologies for the delay in my reply. I am working on a new release that will also contain some additional updates and will try to get it released as soon as I can. Apologies again for the delay in getting the new release out with your pull request, I ran into issues during the CRAN submission process.

**Comment by edmcman** [comment]
No worries.  It's not blocking me or anything.  I ran my script that used PetfindeR on a new machine and installed from CRAN, and so I ran into the problem again.  So I figured I would add a gentle reminder :-)

**Comment by aschleg** [comment]
I appreciate it! I think going forward I may make `devtools::install_github` as the preferred installation approach. Unfortunately, Web APIs and CRAN don't mix together well. I have all the changes ready to go, but submitting to CRAN has been a pain.

That said, if you would like to use the most recent version with your `organization` fix and additional updates, you can definitely run:

`devtools::install_github(aschleg/PetfindeR`

I'll continue trying to get the most recent version up on CRAN, hopefully by the end of the weekend.

**Comment by aschleg** [comment]
Hi Edward!

I hope you are doing well! Just wanted to give you a heads-up that PetfindeR 2.1.0 is now available on CRAN with your change and a few others. Apologies again for the delay, there was some weirdness between my local version and getting it submitted successfully on CRAN that caused some issues. Please let me know if you have any questions! Thank you!

**Comment by edmcman** [comment]
Thanks so much!
